version: '3'
services:

  streamlit:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-image-search
    working_dir: '/app'
    tty: true
    volumes: 
      - ./:/app
    ports: 
      - '8501:8501'
    command: streamlit run app.py